name: CI/CD Pipeline for FireStack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
        continue-on-error: true

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pylint coverage
          npm install -g jest jsdoc cypress eslint
        continue-on-error: true

      - name: Set Environment Variables
        env:
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        run: |
          echo "FLASK_SECRET_KEY=${FLASK_SECRET_KEY}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> $GITHUB_ENV
          echo "REDIRECT_URI=${REDIRECT_URI}" >> $GITHUB_ENV
        continue-on-error: true

  jsdocs:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate JSDocs
        run: npx jsdoc -c jsdoc.json -d jsdocs/

      - name: Push JSDocs to Docs Branch
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Fetch the latest state of the remote repository
          git fetch origin

          # Switch to or create the docs branch
          git checkout -B docs

          # Use a temporary directory to ensure safe copying
          mkdir -p jsdocs_temp
          cp -R jsdocs/* jsdocs_temp/
          rm -rf jsdocs
          mv jsdocs_temp jsdocs

          # Stage and commit the updated documentation
          git add jsdocs/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update JSDocs [skip ci]"

            # Push the changes to the remote docs branch
            git push --force "https://b-ishan:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/<owner>/<repo>.git" docs

          fi

  linting_and_code_quality:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Lint Python Code
        run: |
          black --check .
          flake8 .
          pylint $(find . -name "*.py")
        continue-on-error: true

      - name: Lint JavaScript Code
        run: |
          eslint . .js,.jsx,.ts,.tsx
        continue-on-error: true

      - name: Codacy Analysis
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash
          codacy-analysis-cli analyze --tool pylint
          codacy-analysis-cli analyze --tool eslint
        continue-on-error: true

  static_analysis:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Install ESLint Locally
        run: |
          npm install eslint eslint-plugin-security eslint-plugin-jsdoc
        continue-on-error: true

      - name: Perform Static Analysis
        run: |
          npx eslint "**/*.{js,jsx,ts,tsx}" \
            --plugin security \
            --plugin jsdoc
        continue-on-error: true

      - name: Upload Static Analysis Report
        uses: actions/upload-artifact@v3
        with:
          name: static-analysis-report
          path: ./eslint-report/
        continue-on-error: true

  testing:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Run Python Unit Tests
        run: coverage run -m unittest discover -s tests
        continue-on-error: true

      - name: Jest for JavaScript Unit Testing
        run: jest --coverage
        continue-on-error: true

      - name: Cypress End-to-End Testing
        run: cypress run
        continue-on-error: true

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
        continue-on-error: true

      - name: Upload Coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
        continue-on-error: true

  deployment:
    runs-on: ubuntu-latest
    needs: [linting_and_code_quality, testing]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          --data '{"serviceId": "YOUR_RENDER_SERVICE_ID"}' \
          "https://api.render.com/v1/services/YOUR_SERVICE_ID/deploys"
        continue-on-error: true

  optimization:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Minify CSS and JavaScript
        run: |
          npm install -g terser clean-css-cli
          find static/css -name "*.css" -exec cleancss -o {} {} \;
          find static/js -name "*.js" -exec terser -o {} -- {} \;
        continue-on-error: true

      - name: Upload Optimized Files
        uses: actions/upload-artifact@v3
        with:
          name: optimized-files
          path: static/
        continue-on-error: true
