name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pylint coverage
          npm install -g jest jsdoc cypress

  linting_and_code_quality:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Python Code
        run: |
          black --check .
          flake8 .
          pylint $(find . -name "*.py")

  testing:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python Unit Tests
        run: coverage run -m unittest discover -s tests
      - name: Jest for JavaScript Unit Testing
        run: jest --coverage
      - name: Cypress End-to-End Testing
        run: cypress run
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

  documentation:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Generate Documentation
        run: jsdoc -c jsdoc.json -r .

  # Need to setup the render_api_key when available
  # deployment:
  #   runs-on: ubuntu-latest
  #   needs: [linting_and_code_quality, testing]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3
  #     - name: Deploy to Render
  #       env:
  #         RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
  #       run: |
  #         curl -X POST \
  #         -H "Authorization: Bearer $RENDER_API_KEY" \
  #         -H "Content-Type: application/json" \
  #         --data '{"serviceId": "YOUR_RENDER_SERVICE_ID"}' \
  #         "https://api.render.com/v1/services/YOUR_SERVICE_ID/deploys"
          
  optimization:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Minify CSS and JavaScript
        run: |
          npm install -g terser clean-css-cli
          find static/css -name "*.css" -exec cleancss -o {} {} \;
          find static/js -name "*.js" -exec terser -o {} -- {} \;
      - name: Upload Optimized Files
        uses: actions/upload-artifact@v3
        with:
          name: optimized-files
          path: static/